### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by xgqt** [samrushing/metamath-mode#1]
Please clarify on what license this project should be distributed.

Thank You for Your work on this!

**Comment by samrushing** [comment]
Apologies for the delay.

**Comment by xgqt** [comment]
Thank You.

On October 5, 2022 11:04:30 PM GMT+02:00, Sam Rushing ***@***.***> wrote:
>Apologies for the delay.
>
>

-- 
Have a great day!
~ Maciej XGQT Barć
